export const EVENTS = {
    LOAD_SCENE: "EVENT:SCENE:LOAD",
    ENEMY_SLAIN: "EVENT:ENEMY:SLAIN",
    RESTART_LEVEL: "EVENT:RESTART:LEVEL",
    LEVEL_COMPLETE: "EVENT:LEVEL:COMPLETE",
    SOUND_WIN: "EVENT:SOUND:WIN",
    SOUND_LOSE: "EVENT:SOUND:LOSE",
    SOUND_TOGGLE: "EVENT:SOUND:TOGGLE",
} as const;